---
- name: generate hosts file
  hosts: all
  gather_facts: false
  tasks:
    - name: template hosts file
      template:
        src: hosts.j2
        dest: /etc/hosts
      delegate_to: localhost
      run_once: yes

